### ISSUE TITLE
Switch to DataCite Metadata Schema 4.0

### ISSUE THREAD

**Issue by ioverka** [MPDL/DOI#5]
see http://schema.datacite.org/

Current status: "The DataCite Metadata Schema 4.0 was released on May 14, 2016 and is available in the Test Metadata Store. It will be made available for production use in September 2016."

But: "For our Metadata store all these versions are valid, although only one version is considered preferred at any given moment of time."

Does the release has any impact on DOxI? If not: Only await new version of https://github.com/mpaluch/datacite-metadata-generator and replace the md generator.

**Comment by ioverka** [comment]
DOI with schema v4.0 successfully created on DOxI test: 10.15771/16

**Comment by ioverka** [comment]
POST /doi/{doi} works fine as well: 

```
Response Body
OK (10.15771/IMEJIDEV.3S)
Response Code
201
```

**Comment by ioverka** [comment]
Results from meeting on September 20th:
- Dev team will check why PUT /doi isn't possible with schema v4.0 and ensure that DOxI is agnostic to schema version used (at least v3.1 and v4.0 should be supported)
- Inga checks for new version of metadata generator

**Comment by haarli** [comment]
Version 4.0 worked if the DOI identifier in the  metadat xml matched the given DOI in the PUT /doi/doi method. A v4.0 xml does not contain a v3.1 identifier. Thus, the XSL stylesheet, which is supposed to replace the identifier, just made a copy of the xml and forwarded it to Datacite's MDS, which worked fine.
For automically generated DOIs, this didn't work, because the identifier on the xml never matched the given DOI.
Should work now for both versions and methods.
